### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by SamanehShamshiri** [YukiM00/Backdoored-COVID-Net#4]
I'm trying to run the code:
my python version is 3.6.4
tensorflow-gpu==1.15.0
scikit-learn==0.23.2
numpy==1.19.2
opencv-python==4.4.0.44
matplotlib==3.3.2
Pillow==7.2.0
windows 10
cuda 10
cudnn7.4.2
 I got the following error:
File "train.py", line 125, in <module>
    args.in_tensorname, args.out_tensorname, args.input_size)
  File "D:\worksppace\Backdoored-COVID-Net-main\Backdoored-COVID-Net-main\eval.py", line 23, in eval
    x = process_image_file(os.path.join(testfolder, line[1]), 0.08, input_size)
  File "D:\worksppace\Backdoored-COVID-Net-main\Backdoored-COVID-Net-main\data.py", line 24, in process_image_file
    img = crop_top(img, percent=top_percent)
  File "D:\worksppace\Backdoored-COVID-Net-main\Backdoored-COVID-Net-main\data.py", line 13, in crop_top
    offset = int(img.shape[0] * percent)
AttributeError: 'NoneType' object has no attribute 'shape'

would you please tell me how can I solve it?
Best Regards

**Comment by kztakemoto** [comment]
This is because the construction of the COVIDx dataset (i.e., lindawangg/COVID-Net/create_COVIDx.ipynb) has been changed.

(solution 1)
Use `train_split.txt` and `test_split.txt`, generated when you run `create_COVIDx.ipynb`, instead of `train_COVIDx5_half_1.txt` and `test_COVIDx5_half_1.txt`, respectively. But, note that the results may be not reproduced in this case.

(solution 2)
Use the previous version of the COVDx dataset, used in our study. If you want, we can share the dataset via personal communication.

**Comment by SamanehShamshiri** [comment]
Hi
thank you for your reply, I will be thankful if you send me your dataset first, I try it, If it doesn't work then I will try the first solution.

Thank you very much
Best Regards

Email: samaneh.shamshiri@gmail.com

**Comment by kztakemoto** [comment]
I emailed the URL to download the dataset.
